name: Publish SporeModder FX Release
on: push
  #workflow_dispatch:

jobs:
  compile_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SporeModderFX
        uses: actions/checkout@v1
        with:
          repository: emd4600/SporeModder-FX
          path: SporeModder-FX
          fetch-depth: 0

      - name: Checkout Updater
        uses: actions/checkout@v1
        with:
          path: Updater

      - name: Update reg_file.txt
        uses: ./.github/workflows/update-names-reg.yaml
        with:
          file-name: reg_file.txt
        
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Build with Maven
        run: mvn -B package --file pom.xml

# git log $(git describe --tags --abbrev=0)..HEAD --oneline --format=%s
